FROM tomcat:8.0-alpine
LABEL maintainer="abc@gmail.com"
WORKDIR /usr/local/tomcat/webapps
COPY target/webfile-latest.war /usr/local/tomcat/webapps/webfile-latest.war
EXPOSE 8080
CMD ["catalina.sh", "run"]